# Generated by Django 5.2.6 on 2025-09-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryProduct',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('barcode', models.CharField(max_length=64, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_product',
            },
        ),
    ]
